apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvcc
spec:
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
