apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: postgres-secret-csi
spec:
  provider: azure
  secretObjects:
    - secretName: pgpassword    
      type: Opaque              
      data:
      - objectName: PGPASSWORD
        key: PGPASSWORD
  parameters:
    keyvaultName: <key-vault name>
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "<Client ID MSI>" # the client ID of the MSI  
    cloudName: ""                         
    objects:   |
      array:
        - |
          objectName: PGPASSWORD       
          objectType: secret              
          objectVersion: ""               
    tenantId: <aad tenant> # MS Tenant id:449fbe1d-9c99-4509-9014-4fd5cf25b014