apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: <ACR Name>.azurecr.io/smartbrainapi:v2
        imagePullPolicy: Always
        volumeMounts:
          - name: secrets-store-inline
            mountPath: '/mnt/secrets-store'
            readOnly: true
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-service
          - name:  REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: pguser@<Postgress Name>
          - name: PGHOST
            value: <Postgress Name>.postgres.database.azure.com
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: SSLFLAG
            value: 'true'
          - name: PGPASSWORD
            valueFrom: 
              secretKeyRef: 
                name: pgpassword
                key: PGPASSWORD
          - name: WORKER_URL
            value: worker-service
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 3
          timeoutSeconds: 1
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "postgres-secret-csi"


