apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: postgres-secret-csi
spec:
  provider: azure
  secretObjects:
    - secretName: pgpassword    
      type: Opaque              
      data:
      - objectName: PGPASSWORD
        key: PGPASSWORD
  parameters:
    keyvaultName: kv15591-akscs   
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "bb4c30c7-f354-4c0b-8976-48b217e4d5fd" # the client ID of the MSI  
    cloudName: ""                         
    objects:   |
      array:
        - |
          objectName: PGPASSWORD       
          objectType: secret              
          objectVersion: ""               
    tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014
  