apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-tls-akv
spec:
  provider: azure
  parameters:
    keyvaultName: eslz-kv-7z6cmpr2wmwso
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "16bc5f32-76ba-41f1-896d-e747dd46be48" # the client ID of the MSI created by the 
    objects:  |
      array:
        - |
          objectName: aks-ingress-tls
          objectAlias: aks-ingress-tls
          objectType: secret 
  # The objectType above is "secret" even though the aks-ingress-tls Certificate in the keyvault is certificate type.
  # Also, the appropriate identity will need acces to GET "secrets" from the KV, as well as GET for "certificates"
    tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014
  secretObjects:
    - secretName: aks-tls-akv  # k8s secret manifest will be generated and synced after mounting it from pod/deploy
      type: kubernetes.io/tls
      data:
      - objectName: aks-ingress-tlss # must match the name of certificate in kv
        key: tls.crt
      - objectName: aks-ingress-tlss # must match the name of certificate in kv
        key: tls.key
